invenia/Impute.jl

src/context.jl
Iterating over a DataFrameRow is deprecated since DataFrames 0.15 and will yield values in 0.16. Starting from that version, ` any(ctx.missing, x)` will be enough.
DataFrames 0.16 (https://github.com/JuliaLang/METADATA.jl/pull/20229) cannot be tagged before this is merged and tagged.
=> Fix deprecation with DataFrames 0.15

src/imputors/chain.jl, test/runtests.jl
Closes #33 This allows construction of the `Chain` type using the composition operator (`∘`).
=> Construct chains with the composition operator

Project.toml, src/Impute.jl, src/context.jl, src/imputors.jl, src/imputors/drop.jl, src/imputors/fill.jl, src/imputors/interp.jl, src/imputors/locf.jl, src/imputors/nocb.jl, test/runtests.jl
Closes #32 
- Moved vardim field from imputors to impute! call
- Renamed vardim to dims (e.g., obsdim)
- Add a splitkwargs hack which will identify kwargs for the Imputor constructor and return the remaining kwargs that should be passed to the impute call.
=> Add dims kwarg to impute!

src/context.jl, src/imputors/drop.jl, src/imputors/fill.jl, src/imputors/interp.jl, src/imputors/locf.jl, src/imputors/nocb.jl
Rename `ismissing(ctx, x)` to `ismissing!(ctx, x)` since it is mutating the context.
Closes #29 
NOTE: We aren't deprecating this because it currently isn't an exported API.
=> ismissing -> ismissing!

Project.toml, README.md, docs/src/index.md, src/imputors/drop.jl, src/imputors/fill.jl, test/deprecated.jl, test/runtests.jl
Closes #30 and #27.
NOTE: Since dropobs requires that `parent(data) === data` you may find unexpected behaviour when working with wrapper array types where it'll return the parent type rather than the wrapper type. I'm not sure if there is a good way around this since `setparent!` isn't a thing.
=> Add more tests

test/runtests.jl
As of DataFrames 0.19.2 we can't broadcast over a GroupedDataFrame.
NOTE: This is just fixing the tests and doesn't impact the existing code in any way.
=> No broadcasting over GroupedDataFrame

Project.toml, src/Impute.jl, src/context.jl, test/runtests.jl
We're just gonna drop some global deprecations during package load time, as they're rather noisy and the change is pretty minimal and has been around for ~6 months.
=> Drop global deprecations from package

Project.toml, src/imputors.jl, src/imputors/drop.jl, src/imputors/fill.jl, src/imputors/interp.jl, src/imputors/locf.jl, src/imputors/nocb.jl, src/imputors/srs.jl, test/runtests.jl, test/testutils.jl
- Use TestSuites to avoid mostly duplicated tests for each Imputor type (closes #46)
- Fixes some error conditions with completely missing datasets (closes #45)
- Fixes ambiguity errors when using rowtables
- Fixes deprecation of GroupedDataFrame broadcasting on 0.19.2
TODO:
- ~~[ ] Test chains in the testsuite~~
=> Imputor TestSuites

Project.toml, src/Impute.jl, src/imputors.jl, src/imputors/svd.jl, test/runtests.jl
An implementation of SVD imputation which uses an EM based algorithm.
Steps:
1. Missing values are initially imputed with the means imputations.
2. The `svd` is computed for the initialized dataset and a low rank approximation is generated
3. The original missing values are replaced with the corresponding values in the approximation
3. The previous 2 steps are repeated until convergence (new approximations have little change from existing values) or the max iterations are reached.
Currently, the rank of the approximations increases gradually, but I'm open to other suggestions (references). This PR also includes a couple smoke tests to self document what types of data this method would work well on. For example, datasets with a large number of correlated variables where a small subset of …
=> SVD imputation

Project.toml, src/Impute.jl, src/imputors.jl, src/imputors/knn.jl, test/runtests.jl
Inspired by SVD imputation (#16), I implemented KNN imputation which closes #4 
* Troyanskaya, Olga, et al. "Missing value estimation methods for DNA microarrays." Bioinformatics 17.6 (2001): 520-525.
=> kNN Imputation

Project.toml
Bumps distances to 0.9.
Needed for an internal package to work with KernelFunctions (which requires Distances 0.9)
EDIT: Issues are due to the SRS tests - investigating incororating the solution in #63
=> Bump Distances

.appveyor.yml, .travis.yml, Project.toml, src/imputors.jl, src/imputors/drop.jl, test/runtests.jl
- More strictly handles the row tables special cases (vector that's actually a table). We were previous imputing KeyedArrays as tables because they fit the tables interface... even though we'd typically expect to impute it as an array.
=> Get impute working with AxisKeys.KeyedArrays

docs/src/api/functional.md, docs/src/api/imputors.md, docs/src/walkthroughs/svd.md, src/functional.jl, src/imputors.jl, src/imputors/declaremissings.jl, test/imputors/declaremissings.jl, test/runtests.jl
This minimizes confusion with other types of standardization (e.g., z-scores) and more closely aligns with existing missing functions (e.g., `allowmissing`, `disallowmissing`, `skipmissings`).
Closes #76
=> Rename `Standardize` to `DeclareMissings`

src/Impute.jl, src/chain.jl, src/declaremissings.jl, src/functional.jl, src/imputors.jl, test/chain.jl, test/declaremissings.jl, test/runtests.jl
1. It often won't return the input data type if the input data doesn't allowmissings.
2. The API is sufficiently different in that it doesn't really apply across dimensions like the other imputors.
3. It's actively making more `missing`s rather than estimating realistic values which puts it closer to the Filter method than a a real imputor.
Closes #77
=> DeclareMissings is not a real Imputor

test/chain.jl
Check that we aren't accidentally overwriting our input data. Turns out one particular issue was just that `columntable` doesn't make a copy.
=> Added some Chain mutation tests

src/functional.jl, src/imputors/substitute.jl, src/utils.jl, src/validators/threshold.jl, test/imputors/substitute.jl, test/runtests.jl, test/validators.jl
Most of the extra LOC are for more tests for the new `WeightedThreshold` and `WeightedSubstitute` types
This PR closes #74, closes #79 and closes #81 
NOTE: This seems to be what Distances.jl does between weighted and non-weighted distance types.
=> Separate weighted types

.github/workflows/CI.yml, Project.toml, docs/Manifest.toml, docs/Project.toml, src/functional.jl, src/imputors.jl, src/validators.jl
NOTE: The reason we didn't notice this before was that that Manifest appears to have been cached? Seems like it started failing for more recent build because that cache was no longer around so it started looking for Impute.jl at `/Users/rory/repos/invenia/Impute.jl`
Closes #96
=> Fix Impute path in docs/Manifest.toml

.github/workflows/CI.yml, .github/workflows/CompatHelper.yml, .github/workflows/JuliaNightly.yml, .github/workflows/TagBot.yml, README.md, test/runtests.jl
This pull request sets up the GitHubActions workflow on this repository. cc: @fchorney
=> MassInstallAction: Install the GitHubActions workflow on this repository

.github/workflows/CI.yml
Turns out one of the if checks was wrong. to check if we are running on a scheduled run, it should be `github.event_name == 'schedule'`
=> github.event should be github.event_name

.github/workflows/CI.yml
Ok, so after doing more research, I think the issue is that the slack job defines `needs: test` which says "Only run this once 'test' is done", and it also defines `if: github.event_name == 'schedule'` which says "Only run this when the CI is triggered by the schedule".
The problem is that if `test` fails then the `needs` criteria fails and the job is skipped. If you set the `if` to `if: always()` it will run after `test` regardless if `test` passed or failed. So if we add that to the if criteria, we should get the slack job to run only on the schedule regardless if the tests passed or not. (https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-not-requiring-dependent-jobs-to-be-successful)
p.s. sorry for so many PR's @rofinn
=> Fix the CI Schedule once more

Project.toml
We've only bumped the compat versions of our dependencies and this package isn't 1.0 yet.
=> Bump patch release to 0.6.2

Project.toml, src/imputors/substitute.jl, test/imputors/substitute.jl
Throw debug messages when substitution aren't possible when all values are missing.
=> Substitutions when all missing

Project.toml, src/filter.jl, test/filter.jl
=> Fix dispatch for array that disallows missing

Project.toml, test/imputors/knn.jl
When running `Impute.jl` tests against Julia1.8, we run into a problem when calling the `nrmsd()` function [here](https://github.com/invenia/Impute.jl/blob/master/test/imputors/knn.jl#L69) (from `Distances.jl`, function found [here](https://github.com/JuliaStats/Distances.jl/blob/master/src/metrics.jl#L652)).
There error we get is as follows:
Since there were some changes/refactoring to the `extrema()` function, it created a `MethodError`, where it couldn't match the `adjoint()` method with what we passed in (`adjoint(data)` from within the failing test).
Flipping the two around fixes the tests, but not the root of the problem. I'm not sure if this is the correct solution, or if I have to report this as an issue with `JuliaLang` itself. I know a bunch of other stuff changed around …
=> Fixes compatibility for tests running against Juliav1.8

.github/workflows/CI.yml, Project.toml, src/data.jl, src/imputors/knn.jl
Bump AxisKeys and patch release number.
=> Update Project.toml and DataDep

src/imputors/interp.jl, test/imputors/interp.jl
This is a simple solution for #71.
=> handle interp for integers by casting and rounding (#71)
